---
author: "Panagiotis Anastasakis"
output: pdf_document
header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \usepackage{amsmath}
    \usepackage{algpseudocode}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(20)
```


```{r}

library(ggplot2)
library(patchwork)
library(latex2exp)
library(cowplot)

```



```{r}

n = 1000
p = 100
k = 10
k.est = 20

n.reps = 200


results_misspec_recovery_guide = list("gaussian" = list(), "laplace" = list())

for (sampler in names(results_misspec_recovery_guide)) {
  
  results_misspec_recovery_guide[[sampler]] = list("low" = list(), "high" = list())
  
  for (sparsity in names(results_misspec_recovery_guide[[sampler]])) {
    
    n.captured.components = matrix(NA, nrow = n.reps, ncol = k.est)

    for (jj in 1:n.reps) {
      
      sim_polygenic = polygenic_sim(n = n, p = p, k = k, sampler = sampler, sparsity = sparsity)
      
      W = sim_polygenic$W
      W.xl = sim_polygenic$W.xl
      W.lt = sim_polygenic$W.lt
      
      weights.true = rbind(W.xl, W.lt)
      
      guide.list = get_guide(W, K = k.est, ica_runs = 20, verbose = F)
      
      W.xl.guide = guide.list$W.xl
      W.lt.guide = guide.list$W.lt
      weights.guide = rbind(W.xl.guide, W.lt.guide)
      cqi.vals = get_cqi_values(guide.list$cors.unmix, guide.list$clusters)
      
      matches = get_matched_weights(weights.true, weights.guide, n.variants = n,
                                      return.only.indices = TRUE)[,2]
      
      n.captured.components[jj,] = sapply(1:k.est, function(k.est.ord) {
        length(intersect(matches, order(cqi.vals, decreasing = TRUE)[1:k.est.ord]))
      })
      
      
    }
      
    results_misspec_recovery_guide[[sampler]][[sparsity]] = n.captured.components

    
    print(paste("Simulation for", sampler, "sampler and", sparsity, "sparsity completed."))
  
  }
}



```


### Collecting the data


```{r}


k.est = 20

get_quantiles <- function(values) {
  c(median(values), quantile(values, 0.025), quantile(values, 0.975))
}


## Gaussian sampler, low sparsity

quantiles.gaussian.low.misspec.rec = t(sapply(1:k.est, function(jj) 
  get_quantiles(results_misspec_recovery_guide[["gaussian"]][["low"]][,jj])))

quantiles.gaussian.low.misspec.rec = rbind(c(0,0,0), quantiles.gaussian.low.misspec.rec)

data.misspec.rec.gaussian.low = data.frame(
  k = 0:k.est,
  median = quantiles.gaussian.low.misspec.rec[,1],
  lower = quantiles.gaussian.low.misspec.rec[,2],
  upper = quantiles.gaussian.low.misspec.rec[,3]
)


## Gaussian sampler, high sparsity

quantiles.gaussian.high.misspec.rec = t(sapply(1:k.est, function(jj) 
  get_quantiles(results_misspec_recovery_guide[["gaussian"]][["high"]][,jj])))

quantiles.gaussian.high.misspec.rec = rbind(c(0,0,0), quantiles.gaussian.high.misspec.rec)

data.misspec.rec.gaussian.high = data.frame(
  k = 0:k.est,
  median = quantiles.gaussian.high.misspec.rec[,1],
  lower = quantiles.gaussian.high.misspec.rec[,2],
  upper = quantiles.gaussian.high.misspec.rec[,3]
)



## Laplace sampler, low sparsity

quantiles.laplace.low.misspec.rec = t(sapply(1:k.est, function(jj) 
  get_quantiles(results_misspec_recovery_guide[["laplace"]][["low"]][,jj])))

quantiles.laplace.low.misspec.rec = rbind(c(0,0,0), quantiles.laplace.low.misspec.rec)

data.misspec.rec.laplace.low = data.frame(
  k = 0:k.est,
  median = quantiles.laplace.low.misspec.rec[,1],
  lower = quantiles.laplace.low.misspec.rec[,2],
  upper = quantiles.laplace.low.misspec.rec[,3]
)


## Laplace sampler, high sparsity


quantiles.laplace.high.misspec.rec = t(sapply(1:k.est, function(jj) 
  get_quantiles(results_misspec_recovery_guide[["laplace"]][["high"]][,jj])))

quantiles.laplace.high.misspec.rec = rbind(c(0,0,0), quantiles.laplace.high.misspec.rec)

data.misspec.rec.laplace.high = data.frame(
  k = 0:k.est,
  median = quantiles.laplace.high.misspec.rec[,1],
  lower = quantiles.laplace.high.misspec.rec[,2],
  upper = quantiles.laplace.high.misspec.rec[,3]
)




```



### Plotting the Data


```{r}

plot_rec <- function(data, title, y_breaks, yend = 10, vjust_y = 1) {
  ggplot(data, aes(x = k, y = median)) +
    geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2, fill = "#FF4DB8") + 
    geom_line(linewidth = 1, color = "#FF4DB8") +  
    annotate("segment", x = 0, y = 0, xend = 20, yend = yend, color = "blue", linewidth = 1, linetype = "dashed") +
    labs(title = title, x = "CQI-Ordered GUIDE Components", y = "Matched Components Found") +
    theme_minimal() +
    scale_y_continuous(breaks = y_breaks) +
    scale_x_continuous(breaks = seq(0, 20, by = 4)) +
    theme(legend.position = "none",
          plot.title = element_text(size = 20, hjust = 0.5),
          axis.title.x = element_text(size = 17, vjust = 0.2),
          axis.title.y = element_text(size = 17, vjust = vjust_y),
          axis.text.x = element_text(size = 16),  
          axis.text.y = element_text(size = 14),
          plot.margin = margin(20, 10, 20, 10)) +
    coord_cartesian(xlim = range(data$k), ylim = c(0, yend))
}


p.misspec.rec.gaussian.low <- plot_rec(data.misspec.rec.gaussian.low, "Gaussian Setting, Low Sparsity", y_breaks = seq(0, 10, by = 2))  
p.misspec.rec.gaussian.high <- plot_rec(data.misspec.rec.gaussian.high, "Gaussian Setting, High Sparsity", y_breaks = seq(0, 10, by = 2))  
p.misspec.rec.laplace.low <- plot_rec(data.misspec.rec.laplace.low, "Laplace Setting, Low Sparsity", y_breaks = seq(0, 10, by = 2))  
p.misspec.rec.laplace.high <- plot_rec(data.misspec.rec.laplace.high, "Laplace Setting, High Sparsity", y_breaks = seq(0, 10, by = 2))  

plots_gridmisspec_rec <- plot_grid(
  p.misspec.rec.gaussian.low, p.misspec.rec.gaussian.high,
  p.misspec.rec.laplace.low, p.misspec.rec.laplace.high,
  ncol = 2, align = "hv"
)


final_plot_gridmisspec_rec <- ggdraw() +
  draw_label("Matched Components Found with CQI Ordering", fontface = 'plain', size = 28, hjust = 0.5, vjust = -20.3) +
  draw_plot(
    plot_grid(
      plots_gridmisspec_rec + theme(plot.margin = margin(10, 20, 25, 15))),
    y = -0.03
  )


## save at 16x12 inches
final_plot_gridmisspec_rec


```

