---
author: "Panagiotis Anastasakis"
output: pdf_document

header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \usepackage{amsmath}
    \usepackage{algpseudocode}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(2)
```


```{r}

library(ggplot2)
library(patchwork)
library(latex2exp)
library(cowplot)

```





```{r}


n.reps = 200

n = 1000
p = 100
k = 10

k.est.vals = 2:30


results_misspec = list("gaussian" = list(), "laplace" = list())
sim_list = list("gaussian" = list(), "laplace" = list())
  
for (sampler in names(results_misspec)) {

  results_misspec[[sampler]] = list("low" = list(), "high" = list())
  sim_list[[sampler]] = list("low" = list(), "high" = list())
  
  for (sparsity in names(results_misspec[[sampler]])) {
    
    results_misspec[[sampler]][[sparsity]] = vector("list", length(k.est.vals)+1) ## the first list corresponds to k=1 and is empty
    
    sim_list[[sampler]][[sparsity]] = lapply(1:n.reps, function(...) polygenic_sim(n = n, p = p, k = k, sampler = sampler, sparsity = sparsity)) ## using the same simulated matrices
    
    for (k.est in k.est.vals) {
      
      avg.cor.guide.xl = c()
      avg.cor.guide.lt = c()
      avg.cor.guide.total = c()
      cor.min.guide = c()

      avg.cor.degas.xl = c()
      avg.cor.degas.lt = c()
      avg.cor.degas.total = c()
      
      for (jj in 1:n.reps) {
          
        sim_polygenic = sim_list[[sampler]][[sparsity]][[jj]]
        
        W = sim_polygenic$W
        W.xl = sim_polygenic$W.xl
        W.lt = sim_polygenic$W.lt
        
        weights.true = rbind(W.xl, W.lt)
        
        ## GUIDE
        
        guide.list = get_guide(W, K = k.est, ica_runs = 20, verbose = F)
        
        W.xl.guide = guide.list$W.xl
        W.lt.guide = guide.list$W.lt
        weights.guide = rbind(W.xl.guide, W.lt.guide)
        
        ## DeGAs
        
        degas.list = get_tsvd(scale(W), K = k.est)
        W.xl.degas = degas.list$U
        W.lt.degas = degas.list$V
        weights.degas = rbind(W.xl.degas, W.lt.degas)
        
        if (k.est < k) {
          
          weights.guide.matched = get_matched_weights(weights.true = weights.true,
                                                      weights.estimated = weights.guide,
                                                      n.variants = n)
          
          W.xl.matched = weights.guide.matched$weights.matched.xl
          W.lt.matched = weights.guide.matched$weights.matched.lt
          
          weights.true.matched = rbind(W.xl.matched, W.lt.matched)
          
          avg.cor.guide.xl = c(avg.cor.guide.xl, mean(sapply(1:k.est, function(ii) cor(W.xl.matched[,ii], W.xl.guide[,ii]))))
          avg.cor.guide.lt = c(avg.cor.guide.lt, mean(sapply(1:k.est, function(ii) cor(W.lt.matched[,ii], W.lt.guide[,ii]))))
          
          matched.cors = sapply(1:k.est, function(ii) cor(weights.true.matched[,ii], weights.guide[,ii]))
          cor.min.guide = c(cor.min.guide, min(matched.cors))
          avg.cor.guide.total = c(avg.cor.guide.total, mean(matched.cors))
          
          
          weights.degas.matched = get_matched_weights(weights.true = weights.true,
                                                      weights.estimated = weights.degas,
                                                      n.variants = n)
          
          W.xl.matched = weights.degas.matched$weights.matched.xl
          W.lt.matched = weights.degas.matched$weights.matched.lt
          
          weights.true.matched = rbind(W.xl.matched, W.lt.matched)
          
          matched.cors = sapply(1:k.est, function(ii) cor(weights.true.matched[,ii], weights.degas[,ii]))
          avg.cor.degas.total = c(avg.cor.degas.total, mean(matched.cors))
          
          avg.cor.degas.xl = c(avg.cor.degas.xl, mean(sapply(1:k.est, function(ii) cor(W.xl.matched[,ii], W.xl.degas[,ii]))))
          avg.cor.degas.lt = c(avg.cor.degas.lt, mean(sapply(1:k.est, function(ii) cor(W.lt.matched[,ii], W.lt.degas[,ii]))))
          
        }
          
        else {
            
          weights.guide.matched = get_matched_weights(weights.true = weights.true,
                                                      weights.estimated = weights.guide,
                                                      n.variants = n)
          
          W.xl.guide.matched = weights.guide.matched$weights.matched.xl
          W.lt.guide.matched = weights.guide.matched$weights.matched.lt
          
          weights.guide.matched.total = rbind(W.xl.guide.matched, W.lt.guide.matched)
          
          avg.cor.guide.xl = c(avg.cor.guide.xl, mean(sapply(1:k, function(ii) cor(W.xl[,ii], W.xl.guide.matched[,ii]))))
          avg.cor.guide.lt = c(avg.cor.guide.lt, mean(sapply(1:k, function(ii) cor(W.lt[,ii], W.lt.guide.matched[,ii]))))
          
          matched.cors = sapply(1:k, function(ii) cor(weights.true[,ii], weights.guide.matched.total[,ii]))
          cor.min.guide = c(cor.min.guide, min(matched.cors))
          avg.cor.guide.total = c(avg.cor.guide.total, mean(matched.cors))
          
          
          weights.degas.matched = get_matched_weights(weights.true = weights.true,
                                                      weights.estimated = weights.degas,
                                                      n.variants = n)
          
          W.xl.degas.matched = weights.degas.matched$weights.matched.xl
          W.lt.degas.matched = weights.degas.matched$weights.matched.lt
          
          weights.degas.matched.total = rbind(W.xl.degas.matched, W.lt.degas.matched)
          matched.cors = sapply(1:k, function(ii) cor(weights.true[,ii], weights.degas.matched.total[,ii]))
          
          avg.cor.degas.total = c(avg.cor.degas.total, mean(matched.cors))
          
          avg.cor.degas.xl = c(avg.cor.degas.xl, mean(sapply(1:k, function(ii) cor(W.xl[,ii], W.xl.degas.matched[,ii]))))
          avg.cor.degas.lt = c(avg.cor.degas.lt, mean(sapply(1:k, function(ii) cor(W.lt[,ii], W.lt.degas.matched[,ii]))))
          
        }
      }
      
    results_misspec[[sampler]][[sparsity]][[k.est]][["GUIDE"]] = data.frame(avg.cor.xl = avg.cor.guide.xl,
                                                                            avg.cor.lt = avg.cor.guide.lt,
                                                                            avg.cor.total = avg.cor.guide.total,
                                                                            cor.min = cor.min.guide)
    
    results_misspec[[sampler]][[sparsity]][[k.est]][["DeGAs"]] = data.frame(avg.cor.xl = avg.cor.degas.xl,
                                                                            avg.cor.lt = avg.cor.degas.lt,
                                                                            avg.cor.total = avg.cor.degas.total)

    print(paste("Simulation for k =", k.est, "with", sampler, "sampler and", sparsity, "sparsity completed."))
    }
  }
}



```



### Collecting the data


```{r}


get_quantiles <- function(values) {
  c(median(values), quantile(values, 0.025), quantile(values, 0.975))
}

k.est.vals = 2:30

## Gaussian, low sparsity

quantiles.gaussian.low.guide.xl = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["low"]][[k.est]][["GUIDE"]]$avg.cor.xl)))

quantiles.gaussian.low.guide.lt = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["low"]][[k.est]][["GUIDE"]]$avg.cor.lt)))

quantiles.gaussian.low.guide.total = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["low"]][[k.est]][["GUIDE"]]$avg.cor.total)))

quantiles.gaussian.low.degas.xl = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["low"]][[k.est]][["DeGAs"]]$avg.cor.xl)))

quantiles.gaussian.low.degas.lt = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["low"]][[k.est]][["DeGAs"]]$avg.cor.lt)))

quantiles.gaussian.low.degas.total = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["low"]][[k.est]][["DeGAs"]]$avg.cor.total)))


data.misspec.gaussian.low.xl = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.gaussian.low.guide.xl[,1], quantiles.gaussian.low.degas.xl[,1]),
  lower = c(quantiles.gaussian.low.guide.xl[,2], quantiles.gaussian.low.degas.xl[,2]),
  upper = c(quantiles.gaussian.low.guide.xl[,3], quantiles.gaussian.low.degas.xl[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)

data.misspec.gaussian.low.lt = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.gaussian.low.guide.lt[,1], quantiles.gaussian.low.degas.lt[,1]),
  lower = c(quantiles.gaussian.low.guide.lt[,2], quantiles.gaussian.low.degas.lt[,2]),
  upper = c(quantiles.gaussian.low.guide.lt[,3], quantiles.gaussian.low.degas.lt[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)

data.misspec.gaussian.low.total = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.gaussian.low.guide.total[,1], quantiles.gaussian.low.degas.total[,1]),
  lower = c(quantiles.gaussian.low.guide.total[,2], quantiles.gaussian.low.degas.total[,2]),
  upper = c(quantiles.gaussian.low.guide.total[,3], quantiles.gaussian.low.degas.total[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)


quantiles.gaussian.low.cor.min.guide = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["low"]][[k.est]][["GUIDE"]]$cor.min)))


data.misspec.gaussian.low.cor.min.guide = data.frame(
  k = k.est.vals,
  median = quantiles.gaussian.low.cor.min.guide[,1],
  lower = quantiles.gaussian.low.cor.min.guide[,2],
  upper = quantiles.gaussian.low.cor.min.guide[,3]
)



## Gaussian, high sparsity

quantiles.gaussian.high.guide.xl = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["high"]][[k.est]][["GUIDE"]]$avg.cor.xl)))

quantiles.gaussian.high.guide.lt = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["high"]][[k.est]][["GUIDE"]]$avg.cor.lt)))

quantiles.gaussian.high.guide.total = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["high"]][[k.est]][["GUIDE"]]$avg.cor.total)))

quantiles.gaussian.high.degas.xl = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["high"]][[k.est]][["DeGAs"]]$avg.cor.xl)))

quantiles.gaussian.high.degas.lt = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["high"]][[k.est]][["DeGAs"]]$avg.cor.lt)))

quantiles.gaussian.high.degas.total = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["high"]][[k.est]][["DeGAs"]]$avg.cor.total)))


data.misspec.gaussian.high.xl = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.gaussian.high.guide.xl[,1], quantiles.gaussian.high.degas.xl[,1]),
  lower = c(quantiles.gaussian.high.guide.xl[,2], quantiles.gaussian.high.degas.xl[,2]),
  upper = c(quantiles.gaussian.high.guide.xl[,3], quantiles.gaussian.high.degas.xl[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)

data.misspec.gaussian.high.lt = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.gaussian.high.guide.lt[,1], quantiles.gaussian.high.degas.lt[,1]),
  lower = c(quantiles.gaussian.high.guide.lt[,2], quantiles.gaussian.high.degas.lt[,2]),
  upper = c(quantiles.gaussian.high.guide.lt[,3], quantiles.gaussian.high.degas.lt[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)

data.misspec.gaussian.high.total = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.gaussian.high.guide.total[,1], quantiles.gaussian.high.degas.total[,1]),
  lower = c(quantiles.gaussian.high.guide.total[,2], quantiles.gaussian.high.degas.total[,2]),
  upper = c(quantiles.gaussian.high.guide.total[,3], quantiles.gaussian.high.degas.total[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)


quantiles.gaussian.high.cor.min.guide = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["gaussian"]][["high"]][[k.est]][["GUIDE"]]$cor.min)))


data.misspec.gaussian.high.cor.min.guide = data.frame(
  k = k.est.vals,
  median = quantiles.gaussian.high.cor.min.guide[,1],
  lower = quantiles.gaussian.high.cor.min.guide[,2],
  upper = quantiles.gaussian.high.cor.min.guide[,3]
)



## Laplace, low sparsity

quantiles.laplace.low.guide.xl = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["low"]][[k.est]][["GUIDE"]]$avg.cor.xl)))

quantiles.laplace.low.guide.lt = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["low"]][[k.est]][["GUIDE"]]$avg.cor.lt)))

quantiles.laplace.low.guide.total = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["low"]][[k.est]][["GUIDE"]]$avg.cor.total)))

quantiles.laplace.low.degas.xl = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["low"]][[k.est]][["DeGAs"]]$avg.cor.xl)))

quantiles.laplace.low.degas.lt = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["low"]][[k.est]][["DeGAs"]]$avg.cor.lt)))

quantiles.laplace.low.degas.total = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["low"]][[k.est]][["DeGAs"]]$avg.cor.total)))


data.misspec.laplace.low.xl = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.laplace.low.guide.xl[,1], quantiles.laplace.low.degas.xl[,1]),
  lower = c(quantiles.laplace.low.guide.xl[,2], quantiles.laplace.low.degas.xl[,2]),
  upper = c(quantiles.laplace.low.guide.xl[,3], quantiles.laplace.low.degas.xl[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)

data.misspec.laplace.low.lt = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.laplace.low.guide.lt[,1], quantiles.laplace.low.degas.lt[,1]),
  lower = c(quantiles.laplace.low.guide.lt[,2], quantiles.laplace.low.degas.lt[,2]),
  upper = c(quantiles.laplace.low.guide.lt[,3], quantiles.laplace.low.degas.lt[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)

data.misspec.laplace.low.total = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.laplace.low.guide.total[,1], quantiles.laplace.low.degas.total[,1]),
  lower = c(quantiles.laplace.low.guide.total[,2], quantiles.laplace.low.degas.total[,2]),
  upper = c(quantiles.laplace.low.guide.total[,3], quantiles.laplace.low.degas.total[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)


quantiles.laplace.low.cor.min.guide = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["low"]][[k.est]][["GUIDE"]]$cor.min)))


data.misspec.laplace.low.cor.min.guide = data.frame(
  k = k.est.vals,
  median = quantiles.laplace.low.cor.min.guide[,1],
  lower = quantiles.laplace.low.cor.min.guide[,2],
  upper = quantiles.laplace.low.cor.min.guide[,3]
)



## Laplace, high sparsity

quantiles.laplace.high.guide.xl = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["high"]][[k.est]][["GUIDE"]]$avg.cor.xl)))

quantiles.laplace.high.guide.lt = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["high"]][[k.est]][["GUIDE"]]$avg.cor.lt)))

quantiles.laplace.high.guide.total = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["high"]][[k.est]][["GUIDE"]]$avg.cor.total)))

quantiles.laplace.high.degas.xl = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["high"]][[k.est]][["DeGAs"]]$avg.cor.xl)))

quantiles.laplace.high.degas.lt = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["high"]][[k.est]][["DeGAs"]]$avg.cor.lt)))

quantiles.laplace.high.degas.total = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["high"]][[k.est]][["DeGAs"]]$avg.cor.total)))


data.misspec.laplace.high.xl = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.laplace.high.guide.xl[,1], quantiles.laplace.high.degas.xl[,1]),
  lower = c(quantiles.laplace.high.guide.xl[,2], quantiles.laplace.high.degas.xl[,2]),
  upper = c(quantiles.laplace.high.guide.xl[,3], quantiles.laplace.high.degas.xl[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)

data.misspec.laplace.high.lt = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.laplace.high.guide.lt[,1], quantiles.laplace.high.degas.lt[,1]),
  lower = c(quantiles.laplace.high.guide.lt[,2], quantiles.laplace.high.degas.lt[,2]),
  upper = c(quantiles.laplace.high.guide.lt[,3], quantiles.laplace.high.degas.lt[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)

data.misspec.laplace.high.total = data.frame(
  k = rep(k.est.vals, 2),
  median = c(quantiles.laplace.high.guide.total[,1], quantiles.laplace.high.degas.total[,1]),
  lower = c(quantiles.laplace.high.guide.total[,2], quantiles.laplace.high.degas.total[,2]),
  upper = c(quantiles.laplace.high.guide.total[,3], quantiles.laplace.high.degas.total[,3]),
  Method = factor(rep(c("GUIDE", "DeGAs"), each = length(k.est.vals)), levels = c("GUIDE", "DeGAs"))
)


quantiles.laplace.high.cor.min.guide = t(sapply(k.est.vals, function(k.est) 
  get_quantiles(results_misspec[["laplace"]][["high"]][[k.est]][["GUIDE"]]$cor.min)))


data.misspec.laplace.high.cor.min.guide = data.frame(
  k = k.est.vals,
  median = quantiles.laplace.high.cor.min.guide[,1],
  lower = quantiles.laplace.high.cor.min.guide[,2],
  upper = quantiles.laplace.high.cor.min.guide[,3]
)


```



### Plotting 



```{r}

colors <- c("GUIDE" = "#E69F00", "DeGAs" = "#56B4E9")

plot_misspec <- function(data, title, ylabel) {
  ggplot(data, aes(x = k, y = median, color = Method, fill = Method)) +
    geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.3) +
    geom_line(linewidth = 1) +
    scale_color_manual(values = colors) +
    scale_fill_manual(values = colors) +
    labs(title = title, x = "Number of Components", y = ylabel) +
    theme_minimal() +
    theme(axis.title.x = element_text(size = 17),
          axis.title.y = element_text(size = 17, vjust = 3),
          axis.text.x = element_text(size = 16),  
          axis.text.y = element_text(size = 14)) +
    xlim(0, 30) + 
    ylim(0.3, 1)
}

## Plotting X->L correlations

p.misspec.gaussian.low.xl <- plot_misspec(data.misspec.gaussian.low.xl, "", TeX(r"(Cor($\textbf{W}_{XL}, \tilde{\textbf{W}}_{XL}$))"))
p.misspec.gaussian.low.lt <- plot_misspec(data.misspec.gaussian.low.lt, "", TeX(r"(Cor($\textbf{W}_{TL}, \tilde{\textbf{W}}_{TL}$))"))  
p.misspec.gaussian.high.xl <- plot_misspec(data.misspec.gaussian.high.xl, "", TeX(r"(Cor($\textbf{W}_{XL}, \tilde{\textbf{W}}_{XL}$))"))  
p.misspec.gaussian.high.lt <- plot_misspec(data.misspec.gaussian.high.lt, "", TeX(r"(Cor($\textbf{W}_{TL}, \tilde{\textbf{W}}_{TL}$))"))  

legend <- suppressWarnings(get_legend(p.misspec.gaussian.low.xl + theme(legend.position = "right",
                                                                        legend.text = element_text(size = 16),
                                                                        legend.title = element_text(size = 18),
                                                                        legend.key.size = unit(1.7, "cm"))))

p.misspec.gaussian.low.xl <- p.misspec.gaussian.low.xl + theme(legend.position = "none")
p.misspec.gaussian.low.lt <- p.misspec.gaussian.low.lt + theme(legend.position = "none")
p.misspec.gaussian.high.xl <- p.misspec.gaussian.high.xl + theme(legend.position = "none")
p.misspec.gaussian.high.lt <- p.misspec.gaussian.high.lt + theme(legend.position = "none")

plots_grid_misspec_gaussian <- plot_grid(
  p.misspec.gaussian.low.xl, p.misspec.gaussian.low.lt,
  p.misspec.gaussian.high.xl, p.misspec.gaussian.high.lt,
  ncol = 2, align = "hv"
)


final_plot_misspec_gaussian <- ggdraw() +
  draw_label("Model Misspecification Simulation with Gaussian Setting", fontface = 'plain', size = 28, hjust = 0.5, vjust = -20.3) +
  draw_label("Low Sparsity", x = 0.065, y = 0.96, size = 20, fontface = "bold") +
  draw_label("High Sparsity", x = 0.065, y = 0.48, size = 20, fontface = "bold") +
  draw_plot(
    plot_grid(
      plots_grid_misspec_gaussian + theme(plot.margin = margin(10, 10, 25, 15)), legend,
      ncol = 2, rel_widths = c(1, 0.11)
    ),
    y = -0.03
  )

## save at 16x12 inches
final_plot_misspec_gaussian

```




```{r}

## Plotting Laplace

p.misspec.laplace.low.xl <- plot_misspec(data.misspec.laplace.low.xl, "", TeX(r"(Cor($\textbf{W}_{XL}, \tilde{\textbf{W}}_{XL}$))"))  
p.misspec.laplace.low.lt <- plot_misspec(data.misspec.laplace.low.lt, "", TeX(r"(Cor($\textbf{W}_{TL}, \tilde{\textbf{W}}_{TL}$))"))  
p.misspec.laplace.high.xl <- plot_misspec(data.misspec.laplace.high.xl, "", TeX(r"(Cor($\textbf{W}_{XL}, \tilde{\textbf{W}}_{XL}$))"))  
p.misspec.laplace.high.lt <- plot_misspec(data.misspec.laplace.high.lt, "", TeX(r"(Cor($\textbf{W}_{TL}, \tilde{\textbf{W}}_{TL}$))"))  

legend <- suppressWarnings(get_legend(p.misspec.laplace.low.xl + theme(legend.position = "right",
                                                                       legend.text = element_text(size = 16),  
                                                                       legend.title = element_text(size = 18),
                                                                       legend.key.size = unit(1.7, "cm"))))

p.misspec.laplace.low.xl <- p.misspec.laplace.low.xl + theme(legend.position = "none")
p.misspec.laplace.low.lt <- p.misspec.laplace.low.lt + theme(legend.position = "none")
p.misspec.laplace.high.xl <- p.misspec.laplace.high.xl + theme(legend.position = "none")
p.misspec.laplace.high.lt <- p.misspec.laplace.high.lt + theme(legend.position = "none")

plots_grid_misspec_laplace <- plot_grid(
  p.misspec.laplace.low.xl, p.misspec.laplace.low.lt,
  p.misspec.laplace.high.xl, p.misspec.laplace.high.lt,
  ncol = 2, align = "hv"
)

final_plot_misspec_laplace <- ggdraw() +
  draw_label("Model Misspecification Simulation with Laplace Setting", fontface = 'plain', size = 28, hjust = 0.5, vjust = -20.3) +
  draw_label("Low Sparsity", x = 0.065, y = 0.96, size = 20, fontface = "bold") +
  draw_label("High Sparsity", x = 0.065, y = 0.48, size = 20, fontface = "bold") +
  draw_plot(
    plot_grid(
      plots_grid_misspec_laplace + theme(plot.margin = margin(10, 10, 25, 15)), legend,
      ncol = 2, rel_widths = c(1, 0.12)
    ),
    y = -0.03
  )

## save at 16x12 inches
final_plot_misspec_laplace



```






